#!/bin/bash
reset="\\e[0m"
red="\\e[31m"
fail()    { printf "${red}✖ $*${reset}\n" 1>&2; exit 1; }
[[ -z ${1} ]] &&
  fail "IP/Host is needed"

cd <KEY LOCATION>
ssh -i "<KEY NAME>" \
-o StrictHostKeyChecking=no \
-o UserKnownHostsFile=/dev/null \
ec2-user@${1}

